### ISSUE TITLE
active class on wrapper and link

### ISSUE THREAD

**Issue by danielpuglisi** [comfy/active_link_to#14]
Is there any reason why the active or inactive class is applied to the wrapper and the containing link?

```
<li class='active'><a href='/' class='active'>Home</a></li>
```

The [Readme](https://github.com/twg/active_link_to/blob/master/README.md#more-options) states that the classes will be applied to the wrapper but not to the link itself.

But the tests are doing the opposite: https://github.com/twg/active_link_to/blob/master/test/active_link_to_test.rb#L127-L137

**Comment by MicFin** [comment]
+1 would be nice if it only applied the class to one element or you could choose

**Comment by zrisher** [comment]
Would definitely need the ability to choose, if this gem makes the choice of one or the other it could break a lot of people's CSS. Default should be current behavior of doing it to both.

**Comment by mgrachev** [comment]
:+1:

**Comment by lafeber** [comment]
I'm actually thinking of implementing some of the functionality here in a fork of the [bootstrap helpers gem](http://fullscreen.github.io/bh/) - currently their nav helper automatically implements a 'active' state but only with `current_page?` which is not sufficient.

**Comment by GBH** [comment]
If wrap tag is present, active class will be only found on the wrapper now
