### ISSUE TITLE
Exclude controller/action

### ISSUE THREAD

**Issue by espen** [comfy/active_link_to#24]
It would be nice if it was possible exclude certain actions. `:active => [['people']], :exclude => [[], ['dashboard'] ]`.

This will solve my problem of wanting a link active with just one action. The second link should be active for all other actions:
`:active => [['people'], ['dashboard'] ]`
`:active => [['people']], :exclude => [[], ['dashboard'] ]`

Not sure how big this issue is as it can be solved by manually typing in all other actions.

**Comment by GBH** [comment]
I think it's a bit complicated. I would just make a helper method that returns a boolean: `:active => helper_to_deal_with_controller_logic`
