### ISSUE TITLE
What's changed between v1.0.2 and v1.0.3?

### ISSUE THREAD

**Issue by itsmrwave** [comfy/active_link_to#32]
I just upgraded from `v1.0.3` from `v1.0.2` and I'm experiencing different behaviour (I've built navigation that uses this `active_link_to` helpers extensively).

I'm not here to file a complaint really, just a request that the project have a `CHANGELOG` to show what's been changed/added. Tried looking through the commits and it's a difficult trying to trace all this down especially since a lot of the commits aren't very descriptive as to what's being done.

This way, I can be in a better position to debug and hopefully trace down and articulate what the problem/fix is/could be. Meanwhile, I've rolled back to `v1.0.2`.

**Comment by itsmrwave** [comment]
So it turns out that in `v1.0.3` I get the following results, which are different in  ... `v1.0.2`

```ruby
is_active_link? '#', nil
# true

is_active_link? '#', nil
# true
```

While this is not a bug. I think the project would still make use of a `CHANGELOG` file.

**Comment by GBH** [comment]
It's me being lazy. There were minor changes that should not affect existing installs.
You can always see diff between releases: https://github.com/comfy/active_link_to/compare/v1.0.2...v1.0.3
