### ISSUE TITLE
Add sr-only span alerting screen readers to link's "active" nature

### ISSUE THREAD

**Issue by zrisher** [comfy/active_link_to#35]
Bootstrap now recommends adding a span alerting screenreaders to a link's active status, i.e.

```
<li class="active">
  <a href="#">
    Link <span class="sr-only">(current)</span>
  </a>
</li>
```

since the screen readers would otherwise have no indication.

Would this be an acceptable default for this repo?

**Comment by GBH** [comment]
#48 should take care of this now
