### ISSUE TITLE
Add support of use default params for active link from confige/initializers/active_link_to.rb

### ISSUE THREAD

**Issue by entity1991** [comfy/active_link_to#39]
I need to add param :wrap_tag => :li to each one link. It will be good to set this option to initializers. This way all links will have wrapper by default.

Thanks.

**Comment by Bahanix** [comment]
:+1:

**Comment by GBH** [comment]
This comes up often, but it's easy enough to create a view helper that wraps `active_link_to` or you can override it and then send default params via super()
