### ISSUE TITLE
Add support for links with hashes

### ISSUE THREAD

**Issue by wardpenney** [comfy/active_link_to#42]
Hi! 

This might be possible already, but it does not seem to be working for me. 

I have the following:

`active_link_to "Emissions", city_path(city, anchor: "#city-emissions")` but the presence of the hash is not triggering the link activation.

I have tired `active: :inclusive`, `active: :exclusive`, and `active: :exact`. 

Any tips? 

Thanks

**Comment by GBH** [comment]
Just released v.1.0.4 and I added test that seems to work for your issue: https://github.com/comfy/active_link_to/blob/master/test/active_link_to_test.rb#L138
Please reopen if this is still an issue. Better yet, create a failing test.
