### ISSUE TITLE
active_link_to 'Home' root_path is always active

### ISSUE THREAD

**Issue by Arkilus** [comfy/active_link_to#46]
Creating a `active_link_to 'Home' root_path` makes it always active, no mather which path I am in.

For example, if I visit my `active_link_to 'Books' books_path`, then both the `Books` and the `Home` link get the `active` class.

Tested with `rails 5.0.0.1` and `active_link_to 1.0.3`.

**Comment by Arkilus** [comment]
Nevermind, the problem was I needed to use `active_link_to 'Home' rootpath, active: :exact` instead.

**Comment by Mikopet** [comment]
thanks for the tip. :+1:
