### ISSUE TITLE
Testing active_link_to

### ISSUE THREAD

**Issue by xhocquet** [comfy/active_link_to#47]
Hey there, my team uses `active_link_to` pretty extensively to manage our navigation links. Today I was writing out some pretty complex logic surrounding a nav menu that uses `active_link_to`, but I couldn't figure out how to test the results.

I mirrored your tests by doing
```
require 'active_link_to'
```

Before my tests, but I keep getting `NoMethod` errors every time it hits an `active_link_to` call.

What way would I go about testing this gem within my app, without mocking the entire gem?

**Comment by GBH** [comment]
You should be able to test it just like any view helper. No need to require things. 
```ruby
# test/helpers/navigation_test.rb
class NavigationHelperTest < ActionView::TestCase
  def test_something
    assert is_active_link?(your_path)
  end
end
```
The only catch is that you probably will have to mock request object there. Haven't done much view helper testing lately myself.

**Comment by xhocquet** [comment]
Mocking the request like you guys do in your test helper was the ticket! Thanks for pointing me in the right direction.
