### ISSUE TITLE
active_link_to yields to blocks

### ISSUE THREAD

**Issue by sunnyrjuneja** [comfy/active_link_to#53]
Hello again Comfy,

Thank you for your great gem. It's been very handy. I was wondering if you would accept a pull request for active_link_to to yield to blocks if it's an active link. Here is my use case.

```ruby
<%= active_link_to 'Some Path', some_path(@path) do %>
  <nav>Sub Navigation For Active Tab</nav>
<% end %
```

If not, no worries. I understand this might bloat your gem.

**Comment by GBH** [comment]
It already should be doing that. You have an extra attribute in your snippet though:

```ruby
<%= active_link_to some_path(@path) do %>
  <nav>Sub Navigation For Active Tab</nav>
<% end %>
```

**Comment by sunnyrjuneja** [comment]
Wow, you thought of everything. Thanks!

**Comment by danwetherald** [comment]
This is not true, html passed to the do block will always render.
