### ISSUE TITLE
How to use on name spaced routes?

### ISSUE THREAD

**Issue by r3id** [comfy/active_link_to#57]
I have controllers which use the admin namespace, how do you match the routes then?

for example: 

`active_link_to 'User Edit', edit_user_path(@user), active: [['admin/users', 'admin/userstuff'], []]`

**Comment by GBH** [comment]
That seems right. If it's not highlighting maybe because path should be `edit_admin_user_path(@user)`?

**Comment by saiqulhaq** [comment]
maybe we can close this issue, seems stale
